### ISSUE TITLE
[prettier-plugin-glsl] Error parsing "attribute"

### ISSUE THREAD

**Issue by disambiguator** [NaridaL/glsl-language-toolkit#3]
Hi! I noticed that a vertex shader with a declared `attribute` does not seem to work. This is similar to my bug report in #1.

For example:
```
attribute float displacement;
void main() {
  gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
}
 ```

fails with the error:
```
Error: PARSE ERROR: Expecting: one of these possible Token sequences:
[error]   1. [IDENTIFIER, '(']
[error]   2. [HASH]
[error]   3. [PRAGMA_DIRECTIVE]
[error]   4. ['const', IDENTIFIER, '{']
[error]   5. ['centroid', 'in', IDENTIFIER]
[error]   6. ['centroid', 'out', IDENTIFIER]
[error]   7. ['centroid', 'varying', IDENTIFIER]
[error]   8. ['in', IDENTIFIER, '{']
[error]   9. ['out', IDENTIFIER, '{']
[error]   10. ['varying', IDENTIFIER, '{']
[error]   11. ['uniform', IDENTIFIER, '{']
[error]   12. ['layout', '(', IDENTIFIER]
[error]   13. [INTERPOLATION_QUALIFIER, 'const', IDENTIFIER]
[error]   14. [INTERPOLATION_QUALIFIER, 'centroid', 'in']
[error]   15. [INTERPOLATION_QUALIFIER, 'centroid', 'out']
[error]   16. [INTERPOLATION_QUALIFIER, 'centroid', 'varying']
[error]   17. [INTERPOLATION_QUALIFIER, 'in', IDENTIFIER]
[error]   18. [INTERPOLATION_QUALIFIER, 'out', IDENTIFIER]
[error]   19. [INTERPOLATION_QUALIFIER, 'varying', IDENTIFIER]
[error]   20. [INTERPOLATION_QUALIFIER, 'uniform', IDENTIFIER]
[error]   21. [INTERPOLATION_QUALIFIER, IDENTIFIER, '{']
[error]   22. ['invariant', INTERPOLATION_QUALIFIER, 'const']
[error]   23. ['invariant', INTERPOLATION_QUALIFIER, 'centroid']
[error]   24. ['invariant', INTERPOLATION_QUALIFIER, 'in']
[error]   25. ['invariant', INTERPOLATION_QUALIFIER, 'out']
[error]   26. ['invariant', INTERPOLATION_QUALIFIER, 'varying']
[error]   27. ['invariant', INTERPOLATION_QUALIFIER, 'uniform']
[error]   28. ['invariant', 'const', IDENTIFIER]
[error]   29. ['invariant', 'centroid', 'in']
[error]   30. ['invariant', 'centroid', 'out']
[error]   31. ['invariant', 'centroid', 'varying']
[error]   32. ['invariant', 'in', IDENTIFIER]
[error]   33. ['invariant', 'out', IDENTIFIER]
[error]   34. ['invariant', 'varying', IDENTIFIER]
[error]   35. ['invariant', 'uniform', IDENTIFIER]
[error]   36. [PRECISION_QUALIFIER]
[error]   37. [BASIC_TYPE]
[error]   38. ['void']
[error]   39. ['struct']
[error]   40. ['const', PRECISION_QUALIFIER]
[error]   41. ['const', BASIC_TYPE]
[error]   42. ['const', 'void']
[error]   43. ['const', 'struct']
[error]   44. ['in', PRECISION_QUALIFIER]
[error]   45. ['in', BASIC_TYPE]
[error]   46. ['in', 'void']
[error]   47. ['in', 'struct']
[error]   48. ['out', PRECISION_QUALIFIER]
[error]   49. ['out', BASIC_TYPE]
[error]   50. ['out', 'void']
[error]   51. ['out', 'struct']
[error]   52. ['varying', PRECISION_QUALIFIER]
[error]   53. ['varying', BASIC_TYPE]
[error]   54. ['varying', 'void']
[error]   55. ['varying', 'struct']
[error]   56. ['uniform', PRECISION_QUALIFIER]
[error]   57. ['uniform', BASIC_TYPE]
[error]   58. ['uniform', 'void']
[error]   59. ['uniform', 'struct']
[error]   60. [INTERPOLATION_QUALIFIER, PRECISION_QUALIFIER]
[error]   61. [INTERPOLATION_QUALIFIER, BASIC_TYPE]
[error]   62. [INTERPOLATION_QUALIFIER, 'void']
[error]   63. [INTERPOLATION_QUALIFIER, 'struct']
[error]   64. [IDENTIFIER, '[']
[error]   65. [IDENTIFIER, IDENTIFIER]
[error]   66. [IDENTIFIER, ';']
[error]   67. ['const', IDENTIFIER, '[']
[error]   68. ['const', IDENTIFIER, IDENTIFIER]
[error]   69. ['const', IDENTIFIER, ';']
[error]   70. ['centroid', 'in', PRECISION_QUALIFIER]
[error]   71. ['centroid', 'in', BASIC_TYPE]
[error]   72. ['centroid', 'in', 'void']
[error]   73. ['centroid', 'in', 'struct']
[error]   74. ['centroid', 'in', IDENTIFIER]
[error]   75. ['centroid', 'out', PRECISION_QUALIFIER]
[error]   76. ['centroid', 'out', BASIC_TYPE]
[error]   77. ['centroid', 'out', 'void']
[error]   78. ['centroid', 'out', 'struct']
[error]   79. ['centroid', 'out', IDENTIFIER]
[error]   80. ['centroid', 'varying', PRECISION_QUALIFIER]
[error]   81. ['centroid', 'varying', BASIC_TYPE]
[error]   82. ['centroid', 'varying', 'void']
[error]   83. ['centroid', 'varying', 'struct']
[error]   84. ['centroid', 'varying', IDENTIFIER]
[error]   85. ['in', IDENTIFIER, '[']
[error]   86. ['in', IDENTIFIER, IDENTIFIER]
[error]   87. ['in', IDENTIFIER, ';']
[error]   88. ['out', IDENTIFIER, '[']
[error]   89. ['out', IDENTIFIER, IDENTIFIER]
[error]   90. ['out', IDENTIFIER, ';']
[error]   91. ['varying', IDENTIFIER, '[']
[error]   92. ['varying', IDENTIFIER, IDENTIFIER]
[error]   93. ['varying', IDENTIFIER, ';']
[error]   94. ['uniform', IDENTIFIER, '[']
[error]   95. ['uniform', IDENTIFIER, IDENTIFIER]
[error]   96. ['uniform', IDENTIFIER, ';']
[error]   97. ['layout', '(', IDENTIFIER]
[error]   98. [INTERPOLATION_QUALIFIER, 'const', PRECISION_QUALIFIER]
[error]   99. [INTERPOLATION_QUALIFIER, 'const', BASIC_TYPE]
[error]   100. [INTERPOLATION_QUALIFIER, 'const', 'void']
[error]   101. [INTERPOLATION_QUALIFIER, 'const', 'struct']
[error]   102. [INTERPOLATION_QUALIFIER, 'const', IDENTIFIER]
[error]   103. [INTERPOLATION_QUALIFIER, 'centroid', 'in']
[error]   104. [INTERPOLATION_QUALIFIER, 'centroid', 'out']
[error]   105. [INTERPOLATION_QUALIFIER, 'centroid', 'varying']
[error]   106. [INTERPOLATION_QUALIFIER, 'in', PRECISION_QUALIFIER]
[error]   107. [INTERPOLATION_QUALIFIER, 'in', BASIC_TYPE]
[error]   108. [INTERPOLATION_QUALIFIER, 'in', 'void']
[error]   109. [INTERPOLATION_QUALIFIER, 'in', 'struct']
[error]   110. [INTERPOLATION_QUALIFIER, 'in', IDENTIFIER]
[error]   111. [INTERPOLATION_QUALIFIER, 'out', PRECISION_QUALIFIER]
[error]   112. [INTERPOLATION_QUALIFIER, 'out', BASIC_TYPE]
[error]   113. [INTERPOLATION_QUALIFIER, 'out', 'void']
[error]   114. [INTERPOLATION_QUALIFIER, 'out', 'struct']
[error]   115. [INTERPOLATION_QUALIFIER, 'out', IDENTIFIER]
[error]   116. [INTERPOLATION_QUALIFIER, 'varying', PRECISION_QUALIFIER]
[error]   117. [INTERPOLATION_QUALIFIER, 'varying', BASIC_TYPE]
[error]   118. [INTERPOLATION_QUALIFIER, 'varying', 'void']
[error]   119. [INTERPOLATION_QUALIFIER, 'varying', 'struct']
[error]   120. [INTERPOLATION_QUALIFIER, 'varying', IDENTIFIER]
[error]   121. [INTERPOLATION_QUALIFIER, 'uniform', PRECISION_QUALIFIER]
[error]   122. [INTERPOLATION_QUALIFIER, 'uniform', BASIC_TYPE]
[error]   123. [INTERPOLATION_QUALIFIER, 'uniform', 'void']
[error]   124. [INTERPOLATION_QUALIFIER, 'uniform', 'struct']
[error]   125. [INTERPOLATION_QUALIFIER, 'uniform', IDENTIFIER]
[error]   126. [INTERPOLATION_QUALIFIER, IDENTIFIER, '[']
[error]   127. [INTERPOLATION_QUALIFIER, IDENTIFIER, IDENTIFIER]
[error]   128. [INTERPOLATION_QUALIFIER, IDENTIFIER, ';']
[error]   129. ['invariant', INTERPOLATION_QUALIFIER, 'const']
[error]   130. ['invariant', INTERPOLATION_QUALIFIER, 'centroid']
[error]   131. ['invariant', INTERPOLATION_QUALIFIER, 'in']
[error]   132. ['invariant', INTERPOLATION_QUALIFIER, 'out']
[error]   133. ['invariant', INTERPOLATION_QUALIFIER, 'varying']
[error]   134. ['invariant', INTERPOLATION_QUALIFIER, 'uniform']
[error]   135. ['invariant', 'const', PRECISION_QUALIFIER]
[error]   136. ['invariant', 'const', BASIC_TYPE]
[error]   137. ['invariant', 'const', 'void']
[error]   138. ['invariant', 'const', 'struct']
[error]   139. ['invariant', 'const', IDENTIFIER]
[error]   140. ['invariant', 'centroid', 'in']
[error]   141. ['invariant', 'centroid', 'out']
[error]   142. ['invariant', 'centroid', 'varying']
[error]   143. ['invariant', 'in', PRECISION_QUALIFIER]
[error]   144. ['invariant', 'in', BASIC_TYPE]
[error]   145. ['invariant', 'in', 'void']
[error]   146. ['invariant', 'in', 'struct']
[error]   147. ['invariant', 'in', IDENTIFIER]
[error]   148. ['invariant', 'out', PRECISION_QUALIFIER]
[error]   149. ['invariant', 'out', BASIC_TYPE]
[error]   150. ['invariant', 'out', 'void']
[error]   151. ['invariant', 'out', 'struct']
[error]   152. ['invariant', 'out', IDENTIFIER]
[error]   153. ['invariant', 'varying', PRECISION_QUALIFIER]
[error]   154. ['invariant', 'varying', BASIC_TYPE]
[error]   155. ['invariant', 'varying', 'void']
[error]   156. ['invariant', 'varying', 'struct']
[error]   157. ['invariant', 'varying', IDENTIFIER]
[error]   158. ['invariant', 'uniform', PRECISION_QUALIFIER]
[error]   159. ['invariant', 'uniform', BASIC_TYPE]
[error]   160. ['invariant', 'uniform', 'void']
[error]   161. ['invariant', 'uniform', 'struct']
[error]   162. ['invariant', 'uniform', IDENTIFIER]
[error]   163. ['precision']
[error] but found: 'attribute'
[error] translationUnit > externalDeclaration
[error] ./src/compiler.lambda:1:0
[error] 
[error]     at checkParsingErrors (/Users/paras/workspace/floating_points/node_modules/prettier-plugin-glsl/lib/prettier-plugin.cjs.js:2465:15)
[error]     at parseInput (/Users/paras/workspace/floating_points/node_modules/prettier-plugin-glsl/lib/prettier-plugin.cjs.js:2497:5)
[error]     at Object.parse (/Users/paras/workspace/floating_points/node_modules/prettier-plugin-glsl/lib/prettier-plugin.cjs.js:2581:37)
[error]     at Object.parse (/Users/paras/workspace/floating_points/node_modules/prettier/index.js:7334:23)
[error]     at coreFormat (/Users/paras/workspace/floating_points/node_modules/prettier/index.js:8645:18)
[error]     at formatWithCursor2 (/Users/paras/workspace/floating_points/node_modules/prettier/index.js:8837:18)
[error]     at Object.formatWithCursor (/Users/paras/workspace/floating_points/node_modules/prettier/index.js:37229:12)
[error]     at format (/Users/paras/workspace/floating_points/node_modules/prettier/cli.js:14748:24)
[error]     at formatFiles2 (/Users/paras/workspace/floating_points/node_modules/prettier/cli.js:14860:22)
[error]     at async main (/Users/paras/workspace/floating_points/node_modules/prettier/cli.js:15077:5)
```

**Comment by disambiguator** [comment]
changing to "in" fixes it as a workaround

**Comment by NaridaL** [comment]
similar issue as #1, not a glsl es 3.00 feature. I've added it anyway, give 0.0.6 a try :-)

**Comment by disambiguator** [comment]
Thanks! Just a question - should I report this kind of stuff or are you aiming to _only_ support 3.0? I don't mind updating all my code to new syntax to use this fantastic plugin, I was reporting just in case you wanted to keep some amount of backwards compatibility.

**Comment by NaridaL** [comment]
I was only using the 3.00 spec for main development. These 1.00 keywords were trivial to add so I am fine with that.
