### ISSUE TITLE
Colors package prevents this from working with Prettier's browser bundle

### ISSUE THREAD

**Issue by emilwidlund** [NaridaL/glsl-language-toolkit#8]
Running this plugin with the `prettier/standalone` version in the browser will break the package. The ´os-browserify´ polyfill works fine; but the `colors` package throws. 

```
format(code, { plugins: [glslPrettier], parser: 'glsl-parser' });
```

will generate the following error:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'indexOf')
    at module.exports (has-flag.js:30:1)
    at ../../node_modules/colors/lib/system/supports-colors.js (supports-colors.js:34:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ../../node_modules/colors/lib/colors.js (colors.js:41:24)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ../../node_modules/colors/lib/index.js (index.js:1:14)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
```

I'm able to patch this locally using `patch-package` - but just wanted to make you aware of this. Thanks for this sweet package anyway!

**Comment by NaridaL** [comment]
What config are you using for patch-package?

**Comment by emilwidlund** [comment]
It's an ugly one for now - basically removing the `colors` import and removing the few `x.yellow.underline` references from the common-js bundle, and running `npx patch-package prettier-plugin-glsl` which produces the git patch.

**Comment by NaridaL** [comment]
The colors package should degrade gracefully afaik.

**Comment by NaridaL** [comment]
I think you can get it working if using Webpacks DefinePlugin. https://github.com/Marak/colors.js/issues/193

But... this should work out of the box so I removed this dep :-)

**Comment by NaridaL** [comment]
try 0.0.8
